### ISSUE TITLE
Change Device's Name Endpoint

### ISSUE THREAD

**Issue by julianrod94** [carne-iot/server#21]
User should be able to change each Device's name to organize them.

**Comment by juanmbellini** [comment]
Ya está implementado creo

**Comment by juanmbellini** [comment]
https://github.com/carne-iot/server/blob/9830557c4eb2c42f77614dc585762f2beb00622b/server-webapp/src/main/java/ar/edu/itba/iot/carne_iot/server/web/controller/rest_endpoints/UserEndpoint.java#L364
Acá se puede ver la implementación del endpoint

**Comment by julianrod94** [comment]
Tenes razon. Genial! no lo habia encontrado.

**Comment by juanmbellini** [comment]
👍 
Puedo cerrar el issue?

**Comment by juanmbellini** [comment]
@julianrod94 puedo cerrar esto?
