### ISSUE TITLE
Change Device's Target Temperature Endpoint

### ISSUE THREAD

**Issue by julianrod94** [carne-iot/server#22]
The User should be able to change each Device's Target Temperature Individually so that it's notified when the meat is cooked to his desired state.

**Comment by juanmbellini** [comment]
Okey, pensaba hacer lo siquiente.
Cada vez que vas a cocinar algo, tenés que informar al server que vas a cocinar, y este último prepara todo para que el device pushee los cambios. Onda se crea un "cook".

**Comment by julianrod94** [comment]
La idea seria setear todo antes de cocinar.

**Comment by juanmbellini** [comment]
Por eso, pero no se si guardarlo en el device, o si armar alguna entidad aparte en donde se setean todas las cosas. Por ahi esa entidad puede tener metodos de notificación (por ejemplo, cuando alcanza X temp, cuando alcanza X temp menos un porcentaje, etc), y otras cosas relativas a un proceso de cocción.

**Comment by juanmbellini** [comment]
Se va a hacer desde la app
